### ISSUE TITLE
Add a fast mode

### ISSUE THREAD

**Issue by KittyGiraudel** [HugoGiraudel/node-legofy#1]
Give https://github.com/Automattic/node-canvas#canvasrenderingcontext2dpatternquality and https://github.com/Automattic/node-canvas#canvasrenderingcontext2dfilter a try. If it's efficient, make it an option.

**Comment by HugoGiraudel** [comment]
Completely decent in #17.

**Comment by valeriangalliat** [comment]
Make it configurable. Also allow to configure sample rate for average color computation.

Also allow to configure average color sample rate.
