### ISSUE TITLE
Support GIFs

### ISSUE THREAD

**Issue by KittyGiraudel** [HugoGiraudel/node-legofy#10]
Going to be tough. Not even sure we can do it. :(

Maybe check https://github.com/shachaf/jsgif/blob/master/gif.js?

**Comment by KittyGiraudel** [comment]
So I have been trying to find a way to split the frames of a GIF with Node.js, and as far as I can tell, there is no way to do without having C/C++ bindings. That being said, [gif.js](https://github.com/shachaf/jsgif/blob/master/gif.js) (front-end lib) apparently manages to do it, so maybe there is a chance we could extract the relevant part and port it over to node.

What do you think @valeriangalliat?

**Comment by valeriangalliat** [comment]
Isn't it [Node-compatible](https://github.com/shachaf/jsgif/blob/9e3600862291711119beaf537bce5a61d776f4a2/gif.js#L347-L350) already? Just not published on npm, but not really a problem.

**Comment by KittyGiraudel** [comment]
We could give it a try I guess.

**Comment by valeriangalliat** [comment]
Could use [this](https://www.npmjs.com/package/gif-explode) too, though need native binding.

The good thing is it will be seamless to integrate as we already use streams.

**Comment by KittyGiraudel** [comment]
Mmmh, pretty nice then.

**Comment by valeriangalliat** [comment]
Well we need to build back the GIF, I don't know how to do that though. Unless we just want individual frames LEGOfied?

**Comment by KittyGiraudel** [comment]
Building a GIF from images is very easy. Tons of node packages handle this. Exploding the GIF on frames is much harder.

**Comment by valeriangalliat** [comment]
But using [gifsicle](https://github.com/imagemin/gifsicle-bin) (already a dep of gif-explode) we can do this.

**Comment by valeriangalliat** [comment]
Alright, sweet.

**Comment by valeriangalliat** [comment]
``` js
let i = 0

export const gif = opts =>
  gifExplode(frame => frame
    .pipe(legofy(opts))
    .pipe(fs.createWriteStream('test-' + (i++) + '.gif')))
```

Half the work is done, just need to implode back the GIF!

**Comment by valeriangalliat** [comment]
We'd better abstract this in a `gif-transform` package that would run a transform stream over each frame of a GIF and recompose it back.

Like:

``` js
export const gif = opts => gifTransform(() => legofy(opts))
```

**Comment by KittyGiraudel** [comment]
> We'd better abstract this in a gif-transform package that would run a transform stream over each frame of a GIF and recompose it back.

Ouh, I love how that sounds.

**Comment by valeriangalliat** [comment]
Me 2

**Comment by rluta** [comment]
GIF support works already:

1 - install brew packages `brew install jpeg giflib cairo`
2 - rebuild node-canvas to make sure it picks up the dependencies
3 - enjoy :)

**Comment by valeriangalliat** [comment]
@rluta By GIF we mean animated GIFs, currently we support GIF input but it will take only a single frame if I'm right.

**Comment by KittyGiraudel** [comment]
Oh, yeah @rluta, the issue implies animated GIF, not only the GIF format.

**Comment by valeriangalliat** [comment]
Will not be really useful before we can configure the brick size, because most GIFs are kinda small.

Also currently hard to get a consistent way to explode/implode GIF frames with existing Node.js libraries. Especially since `canvas` cannot output GIF data, involving a conversion from PNG to GIF for each frame or the use of a different library to join the frames.

**Comment by KittyGiraudel** [comment]
Let's consider after #3 then.
