### ISSUE TITLE
Make the number of bricks an option

### ISSUE THREAD

**Issue by KittyGiraudel** [HugoGiraudel/node-legofy#3]

**Comment by HugoGiraudel** [comment]
Once #17 is merged.

**Comment by valeriangalliat** [comment]
By changing the brick size to match the image size when repeated `n` times?

**Comment by KittyGiraudel** [comment]
Yep.

**Comment by valeriangalliat** [comment]
Rather have a vector brick then.

**Comment by KittyGiraudel** [comment]
I have been on the hunt for a SVG version of our brick and unfortunately I could not find one. I even asked on the Python’s version repository, but got no reply. I cannot seem to find a vector version of a top view of a 1&times;1 brick.

So, I suppose we could try stretching the one we have in the mean time. Maybe it would not be that bad given it’s being coloured and seen from the distance. What do you think @valeriangalliat?

**Comment by valeriangalliat** [comment]
Yeah, can do this...

**Comment by KittyGiraudel** [comment]
We need to check the rendering, but that might be decent.
